@startuml
'https://plantuml.com/sequence-diagram

participant "Order service" as order
participant "Product Catalog Service" as product
database "Order Db" as orderDb
database "Event Bus" as kafka

group Process pending order

    order -> kafka : Consume PaymentCompleted Event
    note left
        {
            order_id: number,
            amount: 1000,
            status: 'success'
        }
    end note
    order -> orderDb : Fetch order details from the order db

    order -> product : Update inventory in hand
    note left
        products: [{
            product_id: number,
            quantity: number
        }]
    end note

    product -> order : Return status

    kafka -> product : Consume event OrderReadyForShipment
end

@enduml